# Generated by Django 4.2.4 on 2023-08-31 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0001_initial"),
        ("user", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomName", models.CharField(max_length=63)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Team"), (1, "Group"), (2, "Private")], default=0
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        default="assets/images/people.png", max_length=127
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="team.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRoomShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identify",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Normal"), (1, "Admin"), (2, "Creator")], default=0
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="message.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("size", models.IntegerField()),
                ("type", models.CharField(max_length=15)),
                ("url", models.CharField(max_length=127)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.room",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="user.user",
            ),
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Message"), (1, "Document")], default=0
                    ),
                ),
                ("sender_deleted", models.BooleanField(default=False)),
                ("receiver_deleted", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("checked", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                    ),
                ),
                (
                    "receiver_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_mention",
                        to="user.user",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_mention",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("message__isnull", False),
                    ("document__isnull", False),
                    _connector="OR",
                ),
                name="message_xor_document",
            ),
        ),
    ]
