# Generated by Django 4.2.4 on 2023-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mid',
            field=models.UUIDField(default='F9FF2AB9-D278-0F30-0D79-25488520101E'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagefile',
            name='mid',
            field=models.UUIDField(default='F9FF2AB9-D278-0F30-0D79-25488520101E'),
            preserve_default=False,
        ),
    ]
