# Generated by Django 4.2.4 on 2023-09-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_messagefile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefile',
            name='extension',
            field=models.CharField(default='png', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.message'),
            preserve_default=False,
        ),
    ]
