# Generated by Django 4.2.4 on 2023-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="avatar",
            field=models.CharField(
                default="media/team_avatar/default.jpg", max_length=63
            ),
        ),
    ]
