# Generated by Django 4.2.4 on 2023-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_inv_code_project_preview_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='auto_save',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
