# Generated by Django 4.2.4 on 2023-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=63)),
                ("nickname", models.CharField(max_length=63)),
                ("password", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=63)),
                (
                    "avatar",
                    models.CharField(
                        default="media/avatar/default.jpg", max_length=127
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
            },
        ),
    ]
